=== alegrigoriev/hg2git/hg-config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="Boolean">
		<xs:restriction base="xs:string">
			<xs:enumeration value="1" />
			<xs:enumeration value="Yes" />
			<xs:enumeration value="yes" />
			<xs:enumeration value="True" />
			<xs:enumeration value="true" />
			<xs:enumeration value="0" />
			<xs:enumeration value="No" />
			<xs:enumeration value="no" />
			<xs:enumeration value="False" />
			<xs:enumeration value="false" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="Formatting">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Path" type="xs:string" />
				<xs:element name="NoReindent" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="IndentStyle" use="optional" >
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="tabs" />
						<xs:enumeration value="spaces" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="Indent" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:positiveInteger">
						<xs:maxInclusive value="16"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="TabSize" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:positiveInteger">
						<xs:maxInclusive value="16"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="RetabOnly" type="Boolean" use="optional" />
			<xs:attribute name="IndentCase" type="Boolean" use="optional" />
			<xs:attribute name="FixEOL" type="Boolean" use="optional" />
			<xs:attribute name="FixLastEOL" type="Boolean" use="optional" />
			<xs:attribute name="FormatComments" type="xs:string" use="optional" />
			<xs:attribute name="TrimWhitespace" type="Boolean" use="optional" />
			<xs:attribute name="TrimBackslash" type="Boolean" use="optional" />
			<xs:attribute name="ReindentContinuation" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="MapRef">
		<xs:complexType>
			<xs:all>
				<xs:element name="Ref" type="xs:string" />
				<xs:element minOccurs="0" name="NewRef" type="xs:string" />
			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:element name="InjectFile">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="Path" type="xs:string" use="optional" />
					<xs:attribute name="File" type="xs:string" use="optional" />
					<xs:attribute name="Branch" type="xs:string" use="optional" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="AddFile">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="Path" type="xs:string" use="optional" />
					<xs:attribute name="File" type="xs:string" use="optional" />
					<xs:attribute name="Rev" type="xs:unsignedLong" use="optional" />
					<xs:attribute name="RevId" type="xs:string" use="optional" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="EditMsg">
		<xs:complexType>
			<xs:all>
				<xs:element name="Match" type="xs:string" minOccurs="0"/>
				<xs:element name="Replace" type="xs:string" />
			</xs:all>
			<xs:attribute name="Revs" type="xs:string" use="optional" />
			<xs:attribute name="RevIds" type="xs:string" use="optional" />
			<xs:attribute name="Max" type="xs:unsignedLong" use="optional" />
			<xs:attribute name="Final" type="Boolean" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="SkipCommit">
		<xs:complexType>
			<xs:all>
				<xs:element name="Message" type="xs:string" minOccurs="0" maxOccurs="1" />
			</xs:all>
			<xs:attribute name="Revs" type="xs:string" use="optional" />
			<xs:attribute name="RevIds" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="MapBranch">
		<xs:complexType>
			<xs:all>
				<xs:element maxOccurs="1" name="Branch" type="xs:string" />
				<xs:element minOccurs="0" maxOccurs="1" name="Refname" type="xs:string" />
				<xs:element minOccurs="0" maxOccurs="1" name="RevisionRef" type="xs:string" />
				<xs:element minOccurs="0" ref="EditMsg" />
				<xs:element ref="InjectFile" minOccurs="0" />
				<xs:element name="IgnoreFiles" type="xs:string" minOccurs="0" />
				<xs:element ref="Formatting" minOccurs="0" />
			</xs:all>
			<xs:attribute name="DeleteIfMerged" type="Boolean" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="MapTag">
		<xs:complexType>
			<xs:all>
				<xs:element minOccurs="1" maxOccurs="1" name="Tag" type="xs:string" />
				<xs:element minOccurs="0" maxOccurs="1" name="Refname" type="xs:string" />
			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:group name='Configuration'>
		<xs:sequence>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="Vars">
					<xs:complexType>
						<xs:sequence>
							<xs:choice maxOccurs="unbounded">
								<xs:element name="Branches" type="xs:string" />
								<xs:element name="Tags" type="xs:string" />
							</xs:choice>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Replace">
					<xs:complexType>
						<xs:all>
							<xs:element name="Chars" type="xs:string" />
							<xs:element name="With" type="xs:string" />
						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:element name="Chmod">
					<xs:complexType>
						<xs:all>
							<xs:element name="Path" type="xs:string" />
							<xs:element name="Mode" type="xs:unsignedShort" />
						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:element ref="MapBranch" />
				<xs:element ref="MapTag" />
				<xs:element ref="MapRef" />
				<xs:element ref="EditMsg" />
				<xs:element name="IgnoreFiles" type="xs:string" />
				<xs:element ref="InjectFile" />
				<xs:element name="DeleteFile">
					<xs:complexType>
						<xs:attribute name="Path" type="xs:string" use="required" />
						<xs:attribute name="Rev" type="xs:unsignedLong" use="optional" />
						<xs:attribute name="RevId" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element ref="Formatting" minOccurs="0" />
				<xs:element ref="SkipCommit" minOccurs="0" />
			</xs:choice>
		</xs:sequence>
	</xs:group>

	<xs:element name="Projects">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="1" name="Default">
					<xs:complexType>
						<xs:group minOccurs="0" maxOccurs="unbounded" ref='Configuration' />
						<xs:attribute name="InheritDefault" type="Boolean" use="optional" />
						<xs:attribute name="InheritDefaultMapping" type="Boolean" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Project">
					<xs:complexType>
						<xs:sequence>
							<xs:choice maxOccurs="unbounded">
								<xs:group minOccurs="0" maxOccurs="unbounded" ref='Configuration' />
								<!-- CopyPath can only be present in a Project element -->
								<xs:element name="CopyPath">
									<xs:complexType>
										<xs:all>
											<xs:element name="Path" type="xs:string" />
											<xs:element name="RevId" type="xs:string" minOccurs="0" maxOccurs="1" />
											<xs:element name="Rev" type="xs:unsignedLong" minOccurs="0" maxOccurs="1" />
											<xs:element name="FromPath" type="xs:string" />
											<xs:element name="FromRevId" type="xs:string" minOccurs="0" maxOccurs="1" />
											<xs:element name="FromRev" type="xs:unsignedLong" minOccurs="0" maxOccurs="1" />
										</xs:all>
									</xs:complexType>
								</xs:element>
								<!-- MergeBranch can only be present in a Project element -->
								<xs:element name="MergeBranch">
									<xs:complexType>
										<xs:all>
											<xs:element name="RevId" type="xs:string" minOccurs="0" maxOccurs="1" />
											<xs:element name="Rev" type="xs:unsignedLong" minOccurs="0" maxOccurs="1" />
											<xs:element name="FromRevId" type="xs:string" minOccurs="0" maxOccurs="1" />
											<xs:element name="FromRev" type="xs:unsignedLong" minOccurs="0" maxOccurs="1" />
										</xs:all>
									</xs:complexType>
								</xs:element>
								<xs:element ref="AddFile" />
							</xs:choice>
						</xs:sequence>
						<xs:attribute name="Name" type="xs:string" use="optional" />
						<xs:attribute name="Branch" type="xs:string" use="optional" />
						<xs:attribute name="Refs" type="xs:string" use="optional" />
						<xs:attribute name="InheritDefault" type="Boolean" use="optional" />
						<xs:attribute name="InheritDefaultMapping" type="Boolean" use="optional" />
						<xs:attribute name="ExplicitOnly" type="Boolean" use="optional" />
						<xs:attribute name="NeedsProjects" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== alegrigoriev/hg2git/default-hg-config.xml
<?xml version="1.0" encoding="utf-8"?>
<Projects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation=". hg-config.xsd">
	<Default>
		<!-- These are all default settings -->
		<Vars>
			<Branches>refs/heads/</Branches>
			<Tags>refs/tags/</Tags>
		</Vars>
		<!--
		Replace specification is applied to the path to replace
		names not allowed for refs. The following characters,
		though some of them legal in file names, are not allowed:
		
			Non-printable characters, space ' ', asterisk '*' , colon ':',
			question mark '?', left bracket '[', backslash '\',
			circumflex '^', tilde '~', and also '@{' sequence.
		
		Note that in XML, you don't need to escape a backslash,
		but need to escape some other special characters
		Replace specifications are applied in order of their appearance.
		
		Note that file pathnames are not affected by the
		ref replacement.
		
		You may need custom replacement specifications
		if default replacements create ambiguity (duplicating names).
		-->
		<!--<Replace>
			<Chars>path with spaces</Chars>
			<With>path_without_spaces</With>
		</Replace>-->
		<Replace>
			<!--
			This will replace spaces in the ref names
			with underscores
			-->
			<Chars> </Chars>
			<With>_</With>
		</Replace>
		<Replace>
			<Chars>:</Chars>
			<With>.</With>
		</Replace>
		<Replace>
			<Chars>^</Chars>
			<With>+</With>
		</Replace>
	</Default>
	<Project Name="*" Branch="*">
		<!--
		The default mappings are applied after non-default, for the given path.
		The default replacements are applied after non-default, for the given path.
		-->
		<!-- These are default mappings.
		An asterisk matches any path component (a string without path separator '/')
		A double asterisk matches any number of path components -
		any string with any number of path separators.
		$n are replacement strings, for the corresponding wildcards.
		-->
		<MapBranch>
			<!--
			"<branch>" will map to ref: "refs/heads/<branch>"
			-->
			<Branch>**</Branch>
			<Refname>${Branches}${1}</Refname>
		</MapBranch>
		<MapTag>
			<!--
			"<tag>" will map to ref: "refs/tags/<tag>"
			-->
			<Tag>**</Tag>
			<Refname>${Tags}${1}</Refname>
		</MapTag>

		<!--
		This will inject .editorconfig file to the root directory of each repo
		Default Yes.
		-->
		<InjectFile Path=".editorconfig"># Editor configuration file

# End .editorconfig scan at this directory level
root = true

[**]
charset = utf-8
indent_size = 4
tab_width = 4
insert_final_newline = true
trim_trailing_whitespace = true

[*.{c,cpp,h,hpp}]
indent_style = tab

[*.sh]
indent_style = tab
end_of_line = lf

[*.py]
indent_style = tab

[*.{xml}]
indent_style = tab
indent_size = 2
tab_width = 2

[*{M,m}akefile*]
# Recipe lines in a makefile are starting with a tab character
# Note that you better not use tabs to indent other lines, as it may confuse some versions of Make
indent_style = tab
# Trailing whitespace in makefiles has significance in some cases
trim_trailing_whitespace = false

</InjectFile>
		<!--
		This will inject .gitattributes file to the root directory of each new branch
		-->
		<InjectFile Path=".gitattributes">
*       text=auto
*.c     text
*.h     text
*.cpp   text
*.hpp   text
*.xml   text
*.dsp   text
*.dsw   text
*.vcxproj* text
*.pyproj text
*.exe   binary
*.a     binary
*.lib   binary
*.elf   binary
*.doc   binary
*.docx  binary
*.pdf   binary
*.png   binary
*.jpg   binary

*.sh    text eol=lf
</InjectFile>
		<InjectFile Path=".gitignore">*.o
*.o.d
*.suo
.vs/
.vscode/
.svn/
*~
*.obj
</InjectFile>
	</Project>
</Projects>
